/******************************************************************/
/* Author  : Ahmed Abdallah                                       */
/* Date    : 10/3/2023                                            */
/* SWC     : DMA                                                  */
/* Version : V01                                                  */
/******************************************************************/
#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include "MDMA_interface.h"
#include "MDMA_private.h"
#include "MDMA_config.h"

void MDMA_voidInit()
{
#if MDMA_CHANNEL1_SELECTED_MODE==SELECTED_CHANNEL
	MDMA->CHANNEL[CHANNEL1_ID].CCR&=~(1<<1);
	MDMA->CHANNEL[CHANNEL1_ID].CCR|=(MDMA_CHANNEL1_TRANSFER_COMPELET_INT_STATE<<1);

	MDMA->CHANNEL[CHANNEL1_ID].CCR&=~(1<<2);
	MDMA->CHANNEL[CHANNEL1_ID].CCR|=(MDMA_CHANNEL1_HALF_TRANSFER_COMPELET_INT_STATE<<2);

	MDMA->CHANNEL[CHANNEL1_ID].CCR&=~(1<<3);
	MDMA->CHANNEL[CHANNEL1_ID].CCR|=(MDMA_CHANNEL1_TRANSFER_ERROR_STATE<<3);

	MDMA->CHANNEL[CHANNEL1_ID].CCR&=~(1<<4);
	MDMA->CHANNEL[CHANNEL1_ID].CCR|=(MDMA_CHANNEL1_DIRECTION<<4);

	MDMA->CHANNEL[CHANNEL1_ID].CCR&=~(1<<5);
	MDMA->CHANNEL[CHANNEL1_ID].CCR|=(MDMA_CHANNEL1_CIRCULAR_MODE<<5);

	MDMA->CHANNEL[CHANNEL1_ID].CCR&=~(1<<6);
	MDMA->CHANNEL[CHANNEL1_ID].CCR|=(MDMA_CHANNEL1_PINC<<6);

	MDMA->CHANNEL[CHANNEL1_ID].CCR&=~(1<<7);
	MDMA->CHANNEL[CHANNEL1_ID].CCR|=(MDMA_CHANNEL1_MINC<<7);

	MDMA->CHANNEL[CHANNEL1_ID].CCR&=~(0b11<<8);
	MDMA->CHANNEL[CHANNEL1_ID].CCR|=(MDMA_CHANNEL1_PSIZE<<8);

	MDMA->CHANNEL[CHANNEL1_ID].CCR&=~(0b11<<10);
	MDMA->CHANNEL[CHANNEL1_ID].CCR|=(MDMA_CHANNEL1_MSIZE<<10);

	MDMA->CHANNEL[CHANNEL1_ID].CCR&=~(0b11<<12);
	MDMA->CHANNEL[CHANNEL1_ID].CCR|=(MDMA_CHANNEL1_PRIORITY<<12);

	MDMA->CHANNEL[CHANNEL1_ID].CCR&=~(1<<14);
	MDMA->CHANNEL[CHANNEL1_ID].CCR|=(MDMA_CHANNEL1_M2M_MODE<<14);
#endif
#if MDMA_CHANNEL2_SELECTED_MODE==SELECTED_CHANNEL
	MDMA->CHANNEL[CHANNEL2_ID].CCR&=~(1<<1);
	MDMA->CHANNEL[CHANNEL2_ID].CCR|=(MDMA_CHANNEL2_TRANSFER_COMPELET_INT_STATE<<1);

	MDMA->CHANNEL[CHANNEL2_ID].CCR&=~(1<<2);
	MDMA->CHANNEL[CHANNEL2_ID].CCR|=(MDMA_CHANNEL2_HALF_TRANSFER_COMPELET_INT_STATE<<2);

	MDMA->CHANNEL[CHANNEL2_ID].CCR&=~(1<<3);
	MDMA->CHANNEL[CHANNEL2_ID].CCR|=(MDMA_CHANNEL2_TRANSFER_ERROR_STATE<<3);

	MDMA->CHANNEL[CHANNEL2_ID].CCR&=~(1<<4);
	MDMA->CHANNEL[CHANNEL2_ID].CCR|=(MDMA_CHANNEL2_DIRECTION<<4);

	MDMA->CHANNEL[CHANNEL2_ID].CCR&=~(1<<5);
	MDMA->CHANNEL[CHANNEL2_ID].CCR|=(MDMA_CHANNEL2_CIRCULAR_MODE<<5);

	MDMA->CHANNEL[CHANNEL2_ID].CCR&=~(1<<6);
	MDMA->CHANNEL[CHANNEL2_ID].CCR|=(MDMA_CHANNEL2_PINC<<6);

	MDMA->CHANNEL[CHANNEL2_ID].CCR&=~(1<<7);
	MDMA->CHANNEL[CHANNEL2_ID].CCR|=(MDMA_CHANNEL2_MINC<<7);

	MDMA->CHANNEL[CHANNEL2_ID].CCR&=~(0b11<<8);
	MDMA->CHANNEL[CHANNEL2_ID].CCR|=(MDMA_CHANNEL2_PSIZE<<8);

	MDMA->CHANNEL[CHANNEL2_ID].CCR&=~(0b11<<10);
	MDMA->CHANNEL[CHANNEL2_ID].CCR|=(MDMA_CHANNEL2_MSIZE<<10);

	MDMA->CHANNEL[CHANNEL2_ID].CCR&=~(0b11<<12);
	MDMA->CHANNEL[CHANNEL2_ID].CCR|=(MDMA_CHANNEL2_PRIORITY<<12);

	MDMA->CHANNEL[CHANNEL2_ID].CCR&=~(1<<14);
	MDMA->CHANNEL[CHANNEL2_ID].CCR|=(MDMA_CHANNEL2_M2M_MODE<<14);
#endif
#if MDMA_CHANNEL3_SELECTED_MODE==SELECTED_CHANNEL
	MDMA->CHANNEL[CHANNEL3_ID].CCR&=~(1<<1);
	MDMA->CHANNEL[CHANNEL3_ID].CCR|=(MDMA_CHANNEL3_TRANSFER_COMPELET_INT_STATE<<1);

	MDMA->CHANNEL[CHANNEL3_ID].CCR&=~(1<<2);
	MDMA->CHANNEL[CHANNEL3_ID].CCR|=(MDMA_CHANNEL3_HALF_TRANSFER_COMPELET_INT_STATE<<2);

	MDMA->CHANNEL[CHANNEL3_ID].CCR&=~(1<<3);
	MDMA->CHANNEL[CHANNEL3_ID].CCR|=(MDMA_CHANNEL3_TRANSFER_ERROR_STATE<<3);

	MDMA->CHANNEL[CHANNEL3_ID].CCR&=~(1<<4);
	MDMA->CHANNEL[CHANNEL3_ID].CCR|=(MDMA_CHANNEL3_DIRECTION<<4);

	MDMA->CHANNEL[CHANNEL3_ID].CCR&=~(1<<5);
	MDMA->CHANNEL[CHANNEL3_ID].CCR|=(MDMA_CHANNEL3_CIRCULAR_MODE<<5);

	MDMA->CHANNEL[CHANNEL3_ID].CCR&=~(1<<6);
	MDMA->CHANNEL[CHANNEL3_ID].CCR|=(MDMA_CHANNEL3_PINC<<6);

	MDMA->CHANNEL[CHANNEL3_ID].CCR&=~(1<<7);
	MDMA->CHANNEL[CHANNEL3_ID].CCR|=(MDMA_CHANNEL3_MINC<<7);

	MDMA->CHANNEL[CHANNEL3_ID].CCR&=~(0b11<<8);
	MDMA->CHANNEL[CHANNEL3_ID].CCR|=(MDMA_CHANNEL3_PSIZE<<8);

	MDMA->CHANNEL[CHANNEL3_ID].CCR&=~(0b11<<10);
	MDMA->CHANNEL[CHANNEL3_ID].CCR|=(MDMA_CHANNEL3_MSIZE<<10);

	MDMA->CHANNEL[CHANNEL3_ID].CCR&=~(0b11<<12);
	MDMA->CHANNEL[CHANNEL3_ID].CCR|=(MDMA_CHANNEL3_PRIORITY<<12);

	MDMA->CHANNEL[CHANNEL3_ID].CCR&=~(1<<14);
	MDMA->CHANNEL[CHANNEL3_ID].CCR|=(MDMA_CHANNEL3_M2M_MODE<<14);
#endif
#if MDMA_CHANNEL4_SELECTED_MODE==SELECTED_CHANNEL
	MDMA->CHANNEL[CHANNEL4_ID].CCR&=~(1<<1);
	MDMA->CHANNEL[CHANNEL4_ID].CCR|=(MDMA_CHANNEL4_TRANSFER_COMPELET_INT_STATE<<1);

	MDMA->CHANNEL[CHANNEL4_ID].CCR&=~(1<<2);
	MDMA->CHANNEL[CHANNEL4_ID].CCR|=(MDMA_CHANNEL4_HALF_TRANSFER_COMPELET_INT_STATE<<2);

	MDMA->CHANNEL[CHANNEL4_ID].CCR&=~(1<<3);
	MDMA->CHANNEL[CHANNEL4_ID].CCR|=(MDMA_CHANNEL4_TRANSFER_ERROR_STATE<<3);

	MDMA->CHANNEL[CHANNEL4_ID].CCR&=~(1<<4);
	MDMA->CHANNEL[CHANNEL4_ID].CCR|=(MDMA_CHANNEL4_DIRECTION<<4);

	MDMA->CHANNEL[CHANNEL4_ID].CCR&=~(1<<5);
	MDMA->CHANNEL[CHANNEL4_ID].CCR|=(MDMA_CHANNEL4_CIRCULAR_MODE<<5);

	MDMA->CHANNEL[CHANNEL4_ID].CCR&=~(1<<6);
	MDMA->CHANNEL[CHANNEL4_ID].CCR|=(MDMA_CHANNEL4_PINC<<6);

	MDMA->CHANNEL[CHANNEL4_ID].CCR&=~(1<<7);
	MDMA->CHANNEL[CHANNEL4_ID].CCR|=(MDMA_CHANNEL4_MINC<<7);

	MDMA->CHANNEL[CHANNEL4_ID].CCR&=~(0b11<<8);
	MDMA->CHANNEL[CHANNEL4_ID].CCR|=(MDMA_CHANNEL4_PSIZE<<8);

	MDMA->CHANNEL[CHANNEL4_ID].CCR&=~(0b11<<10);
	MDMA->CHANNEL[CHANNEL4_ID].CCR|=(MDMA_CHANNEL4_MSIZE<<10);

	MDMA->CHANNEL[CHANNEL4_ID].CCR&=~(0b11<<12);
	MDMA->CHANNEL[CHANNEL4_ID].CCR|=(MDMA_CHANNEL4_PRIORITY<<12);

	MDMA->CHANNEL[CHANNEL4_ID].CCR&=~(1<<14);
	MDMA->CHANNEL[CHANNEL4_ID].CCR|=(MDMA_CHANNEL4_M2M_MODE<<14);
#endif
#if MDMA_CHANNEL5_SELECTED_MODE==SELECTED_CHANNEL
	MDMA->CHANNEL[CHANNEL5_ID].CCR&=~(1<<1);
	MDMA->CHANNEL[CHANNEL5_ID].CCR|=(MDMA_CHANNEL5_TRANSFER_COMPELET_INT_STATE<<1);

	MDMA->CHANNEL[CHANNEL5_ID].CCR&=~(1<<2);
	MDMA->CHANNEL[CHANNEL5_ID].CCR|=(MDMA_CHANNEL5_HALF_TRANSFER_COMPELET_INT_STATE<<2);

	MDMA->CHANNEL[CHANNEL5_ID].CCR&=~(1<<3);
	MDMA->CHANNEL[CHANNEL5_ID].CCR|=(MDMA_CHANNEL5_TRANSFER_ERROR_STATE<<3);

	MDMA->CHANNEL[CHANNEL5_ID].CCR&=~(1<<4);
	MDMA->CHANNEL[CHANNEL5_ID].CCR|=(MDMA_CHANNEL5_DIRECTION<<4);

	MDMA->CHANNEL[CHANNEL5_ID].CCR&=~(1<<5);
	MDMA->CHANNEL[CHANNEL5_ID].CCR|=(MDMA_CHANNEL5_CIRCULAR_MODE<<5);

	MDMA->CHANNEL[CHANNEL5_ID].CCR&=~(1<<6);
	MDMA->CHANNEL[CHANNEL5_ID].CCR|=(MDMA_CHANNEL5_PINC<<6);

	MDMA->CHANNEL[CHANNEL5_ID].CCR&=~(1<<7);
	MDMA->CHANNEL[CHANNEL5_ID].CCR|=(MDMA_CHANNEL5_MINC<<7);

	MDMA->CHANNEL[CHANNEL5_ID].CCR&=~(0b11<<8);
	MDMA->CHANNEL[CHANNEL5_ID].CCR|=(MDMA_CHANNEL5_PSIZE<<8);

	MDMA->CHANNEL[CHANNEL5_ID].CCR&=~(0b11<<10);
	MDMA->CHANNEL[CHANNEL5_ID].CCR|=(MDMA_CHANNEL5_MSIZE<<10);

	MDMA->CHANNEL[CHANNEL5_ID].CCR&=~(0b11<<12);
	MDMA->CHANNEL[CHANNEL5_ID].CCR|=(MDMA_CHANNEL5_PRIORITY<<12);

	MDMA->CHANNEL[CHANNEL5_ID].CCR&=~(1<<14);
	MDMA->CHANNEL[CHANNEL5_ID].CCR|=(MDMA_CHANNEL5_M2M_MODE<<14);
#endif
#if MDMA_CHANNEL6_SELECTED_MODE==SELECTED_CHANNEL
	MDMA->CHANNEL[CHANNEL6_ID].CCR&=~(1<<1);
	MDMA->CHANNEL[CHANNEL6_ID].CCR|=(MDMA_CHANNEL6_TRANSFER_COMPELET_INT_STATE<<1);

	MDMA->CHANNEL[CHANNEL6_ID].CCR&=~(1<<2);
	MDMA->CHANNEL[CHANNEL6_ID].CCR|=(MDMA_CHANNEL6_HALF_TRANSFER_COMPELET_INT_STATE<<2);

	MDMA->CHANNEL[CHANNEL6_ID].CCR&=~(1<<3);
	MDMA->CHANNEL[CHANNEL6_ID].CCR|=(MDMA_CHANNEL6_TRANSFER_ERROR_STATE<<3);

	MDMA->CHANNEL[CHANNEL6_ID].CCR&=~(1<<4);
	MDMA->CHANNEL[CHANNEL6_ID].CCR|=(MDMA_CHANNEL6_DIRECTION<<4);

	MDMA->CHANNEL[CHANNEL6_ID].CCR&=~(1<<5);
	MDMA->CHANNEL[CHANNEL6_ID].CCR|=(MDMA_CHANNEL6_CIRCULAR_MODE<<5);

	MDMA->CHANNEL[CHANNEL6_ID].CCR&=~(1<<6);
	MDMA->CHANNEL[CHANNEL6_ID].CCR|=(MDMA_CHANNEL6_PINC<<6);

	MDMA->CHANNEL[CHANNEL6_ID].CCR&=~(1<<7);
	MDMA->CHANNEL[CHANNEL6_ID].CCR|=(MDMA_CHANNEL6_MINC<<7);

	MDMA->CHANNEL[CHANNEL6_ID].CCR&=~(0b11<<8);
	MDMA->CHANNEL[CHANNEL6_ID].CCR|=(MDMA_CHANNEL6_PSIZE<<8);

	MDMA->CHANNEL[CHANNEL6_ID].CCR&=~(0b11<<10);
	MDMA->CHANNEL[CHANNEL6_ID].CCR|=(MDMA_CHANNEL6_MSIZE<<10);

	MDMA->CHANNEL[CHANNEL6_ID].CCR&=~(0b11<<12);
	MDMA->CHANNEL[CHANNEL6_ID].CCR|=(MDMA_CHANNEL6_PRIORITY<<12);

	MDMA->CHANNEL[CHANNEL6_ID].CCR&=~(1<<14);
	MDMA->CHANNEL[CHANNEL6_ID].CCR|=(MDMA_CHANNEL6_M2M_MODE<<14);
#endif
#if MDMA_CHANNEL7_SELECTED_MODE==SELECTED_CHANNEL
	MDMA->CHANNEL[CHANNEL7_ID].CCR&=~(1<<1);
	MDMA->CHANNEL[CHANNEL7_ID].CCR|=(MDMA_CHANNEL7_TRANSFER_COMPELET_INT_STATE<<1);

	MDMA->CHANNEL[CHANNEL7_ID].CCR&=~(1<<2);
	MDMA->CHANNEL[CHANNEL7_ID].CCR|=(MDMA_CHANNEL7_HALF_TRANSFER_COMPELET_INT_STATE<<2);

	MDMA->CHANNEL[CHANNEL7_ID].CCR&=~(1<<3);
	MDMA->CHANNEL[CHANNEL7_ID].CCR|=(MDMA_CHANNEL7_TRANSFER_ERROR_STATE<<3);

	MDMA->CHANNEL[CHANNEL7_ID].CCR&=~(1<<4);
	MDMA->CHANNEL[CHANNEL7_ID].CCR|=(MDMA_CHANNEL7_DIRECTION<<4);

	MDMA->CHANNEL[CHANNEL7_ID].CCR&=~(1<<5);
	MDMA->CHANNEL[CHANNEL7_ID].CCR|=(MDMA_CHANNEL7_CIRCULAR_MODE<<5);

	MDMA->CHANNEL[CHANNEL7_ID].CCR&=~(1<<6);
	MDMA->CHANNEL[CHANNEL7_ID].CCR|=(MDMA_CHANNEL7_PINC<<6);

	MDMA->CHANNEL[CHANNEL7_ID].CCR&=~(1<<7);
	MDMA->CHANNEL[CHANNEL7_ID].CCR|=(MDMA_CHANNEL7_MINC<<7);

	MDMA->CHANNEL[CHANNEL7_ID].CCR&=~(0b11<<8);
	MDMA->CHANNEL[CHANNEL7_ID].CCR|=(MDMA_CHANNEL7_PSIZE<<8);

	MDMA->CHANNEL[CHANNEL7_ID].CCR&=~(0b11<<10);
	MDMA->CHANNEL[CHANNEL7_ID].CCR|=(MDMA_CHANNEL7_MSIZE<<10);

	MDMA->CHANNEL[CHANNEL7_ID].CCR&=~(0b11<<12);
	MDMA->CHANNEL[CHANNEL7_ID].CCR|=(MDMA_CHANNEL7_PRIORITY<<12);

	MDMA->CHANNEL[CHANNEL7_ID].CCR&=~(1<<14);
	MDMA->CHANNEL[CHANNEL7_ID].CCR|=(MDMA_CHANNEL7_M2M_MODE<<14);
#endif

}
void MDMA_voidChannelStart(u8 Copy_u8ChannelId,u32 * Copy_pu32PeriAddress,u32 * Copy_pu32MemoryAddress,u16 Copy_u16DataSize)
{
	CLR_BIT(MDMA->CHANNEL[Copy_u8ChannelId].CCR,0);
	MDMA->CHANNEL[Copy_u8ChannelId].CNDTR=Copy_u16DataSize;
	MDMA->CHANNEL[Copy_u8ChannelId].CPAR=Copy_pu32PeriAddress;
	MDMA->CHANNEL[Copy_u8ChannelId].CMAR=Copy_pu32MemoryAddress;
	SET_BIT(MDMA->CHANNEL[Copy_u8ChannelId].CCR,0);
}
void MDMA_voidClrFlag()
{
	MDMA->IFCR=1<<0;
	MDMA->IFCR=1<<1;
}
