/******************************************************************/
/* Author  : Ahmed Abdallah                                       */
/* Date    : 10/3/2023                                            */
/* SWC     : DMA                                              */
/* Version : V01                                                  */
/******************************************************************/
#ifndef MDMA_CONFIG_H
#define MDMA_CONFIG_H

#define MDMA_CHANNEL1_SELECTED_MODE         SELECTED_CHANNEL
#define MDMA_CHANNEL1_TRANSFER_COMPELET_INT_STATE                   TRANSFER_COMPELET_INT_ENABLE
#define MDMA_CHANNEL1_HALF_TRANSFER_COMPELET_INT_STATE              HALF_TRANSFER_COMPELET_INT_DISABLE
#define MDMA_CHANNEL1_TRANSFER_ERROR_STATE                          TRANSFER_ERROR_INT_DISABLE
#define MDMA_CHANNEL1_M2M_MODE              ENABLE_M2M_MODE
#define MDMA_CHANNEL1_DIRECTION             MEMORY_TO_PERIPHERAL
#define MDMA_CHANNEL1_CIRCULAR_MODE         DISABLE_CIRCULAR_MODE
#define MDMA_CHANNEL1_PINC                  ENABLE_PINC
#define MDMA_CHANNEL1_MINC                  ENABLE_MINC
#define MDMA_CHANNEL1_PSIZE                 PSIZE_32_BIT
#define MDMA_CHANNEL1_MSIZE                 MSIZE_32_BIT
#define MDMA_CHANNEL1_PRIORITY              HIGH_PRIORITY

#define MDMA_CHANNEL2_SELECTED_MODE         UNSELECTED_CHANNEL
#define MDMA_CHANNEL2_TRANSFER_COMPELET_INT_STATE                   TRANSFER_COMPELET_INT_ENABLE
#define MDMA_CHANNEL2_HALF_TRANSFER_COMPELET_INT_STATE              HALF_TRANSFER_COMPELET_INT_DISABLE
#define MDMA_CHANNEL2_TRANSFER_ERROR_STATE                          TRANSFER_ERROR_INT_DISABLE
#define MDMA_CHANNEL2_M2M_MODE              ENABLE_M2M_MODE
#define MDMA_CHANNEL2_DIRECTION             PERIPHERAL_TO_MEMORY
#define MDMA_CHANNEL2_CIRCULAR_MODE         DISABLE_CIRCULAR_MODE
#define MDMA_CHANNEL2_PINC                  ENABLE_PINC
#define MDMA_CHANNEL2_MINC                  ENABLE_MINC
#define MDMA_CHANNEL2_PSIZE                 PSIZE_32_BIT
#define MDMA_CHANNEL2_MSIZE                 MSIZE_32_BIT
#define MDMA_CHANNEL2_PRIORITY              HIGH_PRIORITY


#define MDMA_CHANNEL3_SELECTED_MODE         UNSELECTED_CHANNEL
#define MDMA_CHANNEL3_TRANSFER_COMPELET_INT_STATE                   TRANSFER_COMPELET_INT_ENABLE
#define MDMA_CHANNEL3_HALF_TRANSFER_COMPELET_INT_STATE              HALF_TRANSFER_COMPELET_INT_DISABLE
#define MDMA_CHANNEL3_TRANSFER_ERROR_STATE                          TRANSFER_ERROR_INT_DISABLE
#define MDMA_CHANNEL3_M2M_MODE              ENABLE_M2M_MODE
#define MDMA_CHANNEL3_DIRECTION             PERIPHERAL_TO_MEMORY
#define MDMA_CHANNEL3_CIRCULAR_MODE         DISABLE_CIRCULAR_MODE
#define MDMA_CHANNEL3_PINC                  ENABLE_PINC
#define MDMA_CHANNEL3_MINC                  ENABLE_MINC
#define MDMA_CHANNEL3_PSIZE                 PSIZE_32_BIT
#define MDMA_CHANNEL3_MSIZE                 MSIZE_32_BIT
#define MDMA_CHANNEL3_PRIORITY              HIGH_PRIORITY

#define MDMA_CHANNEL4_SELECTED_MODE         UNSELECTED_CHANNEL
#define MDMA_CHANNEL4_TRANSFER_COMPELET_INT_STATE                   TRANSFER_COMPELET_INT_ENABLE
#define MDMA_CHANNEL4_HALF_TRANSFER_COMPELET_INT_STATE              HALF_TRANSFER_COMPELET_INT_DISABLE
#define MDMA_CHANNEL4_TRANSFER_ERROR_STATE                          TRANSFER_ERROR_INT_DISABLE
#define MDMA_CHANNEL4_M2M_MODE              ENABLE_M2M_MODE
#define MDMA_CHANNEL4_DIRECTION             PERIPHERAL_TO_MEMORY
#define MDMA_CHANNEL4_CIRCULAR_MODE         DISABLE_CIRCULAR_MODE
#define MDMA_CHANNEL4_PINC                  ENABLE_PINC
#define MDMA_CHANNEL4_MINC                  ENABLE_MINC
#define MDMA_CHANNEL4_PSIZE                 PSIZE_32_BIT
#define MDMA_CHANNEL4_MSIZE                 MSIZE_32_BIT
#define MDMA_CHANNEL4_PRIORITY              HIGH_PRIORITY

#define MDMA_CHANNEL5_SELECTED_MODE         UNSELECTED_CHANNEL
#define MDMA_CHANNEL5_TRANSFER_COMPELET_INT_STATE                   TRANSFER_COMPELET_INT_ENABLE
#define MDMA_CHANNEL5_HALF_TRANSFER_COMPELET_INT_STATE              HALF_TRANSFER_COMPELET_INT_DISABLE
#define MDMA_CHANNEL5_TRANSFER_ERROR_STATE                          TRANSFER_ERROR_INT_DISABLE
#define MDMA_CHANNEL5_M2M_MODE              ENABLE_M2M_MODE
#define MDMA_CHANNEL5_DIRECTION             PERIPHERAL_TO_MEMORY
#define MDMA_CHANNEL5_CIRCULAR_MODE         DISABLE_CIRCULAR_MODE
#define MDMA_CHANNEL5_PINC                  ENABLE_PINC
#define MDMA_CHANNEL5_MINC                  ENABLE_MINC
#define MDMA_CHANNEL5_PSIZE                 PSIZE_32_BIT
#define MDMA_CHANNEL5_MSIZE                 MSIZE_32_BIT
#define MDMA_CHANNEL5_PRIORITY              HIGH_PRIORITY


#define MDMA_CHANNEL6_SELECTED_MODE         UNSELECTED_CHANNEL
#define MDMA_CHANNEL6_TRANSFER_COMPELET_INT_STATE                   TRANSFER_COMPELET_INT_ENABLE
#define MDMA_CHANNEL6_HALF_TRANSFER_COMPELET_INT_STATE              HALF_TRANSFER_COMPELET_INT_DISABLE
#define MDMA_CHANNEL6_TRANSFER_ERROR_STATE                          TRANSFER_ERROR_INT_DISABLE
#define MDMA_CHANNEL6_M2M_MODE              ENABLE_M2M_MODE
#define MDMA_CHANNEL6_DIRECTION             PERIPHERAL_TO_MEMORY
#define MDMA_CHANNEL6_CIRCULAR_MODE         DISABLE_CIRCULAR_MODE
#define MDMA_CHANNEL6_PINC                  ENABLE_PINC
#define MDMA_CHANNEL6_MINC                  ENABLE_MINC
#define MDMA_CHANNEL6_PSIZE                 PSIZE_32_BIT
#define MDMA_CHANNEL6_MSIZE                 MSIZE_32_BIT
#define MDMA_CHANNEL6_PRIORITY              HIGH_PRIORITY


#define MDMA_CHANNEL7_SELECTED_MODE         UNSELECTED_CHANNEL
#define MDMA_CHANNEL7_TRANSFER_COMPELET_INT_STATE                   TRANSFER_COMPELET_INT_ENABLE
#define MDMA_CHANNEL7_HALF_TRANSFER_COMPELET_INT_STATE              HALF_TRANSFER_COMPELET_INT_DISABLE
#define MDMA_CHANNEL7_TRANSFER_ERROR_STATE                          TRANSFER_ERROR_INT_DISABLE
#define MDMA_CHANNEL7_M2M_MODE              ENABLE_M2M_MODE
#define MDMA_CHANNEL7_DIRECTION             PERIPHERAL_TO_MEMORY
#define MDMA_CHANNEL7_CIRCULAR_MODE         DISABLE_CIRCULAR_MODE
#define MDMA_CHANNEL7_PINC                  ENABLE_PINC
#define MDMA_CHANNEL7_MINC                  ENABLE_MINC
#define MDMA_CHANNEL7_PSIZE                 PSIZE_32_BIT
#define MDMA_CHANNEL7_MSIZE                 MSIZE_32_BIT
#define MDMA_CHANNEL7_PRIORITY              HIGH_PRIORITY






#endif
